spring:
  profiles: local
  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bluff?useSSL=false&characterEncoding=UTF-8
    #url: jdbc:mysql://192.168.99.100:3306/sample?useSSL=false&characterEncoding=UTF-8
    username: root
    password: passw0rd
    ##driver-class-name: org.h2.Driver
    ##url: jdbc:h2:tcp://localhost/~/test
    ##username: sa
  jpa:
    show-sql: false
    hibernate:
      ddl-auto:
    open-in-view:


